global: 
  scrape_interval: 1m

scrape_configs: 
  - job_name: "prometheus" 
    scrape_interval: 1m 
    static_configs: 
    - targets: ['192.168.1.9:9090']

  - job_name: "node" 
    static_configs: 
    - targets: ['node-exporter:9100']

  - job_name: "cadvisor" 
    scrape_interval: 5s 
    static_configs: 
    - targets: ['cadvisor:8080']  

  - job_name: "kylePC"
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.1.187:9182']

  - job_name: "bryneePC"
    scrape_interval: 5s
    static_configs:
    - targets: ['192.168.1.208:9182']
